name: openjdk-8-windowsservercore

on:
  push:
    branches:
    - master
    paths:
    - 'openjdk-8-windowsservercore/**'
    - 'tests/**'
    - github-action.ps1
    - '!tests/*.bats'
    - '!tests/*.bash'
    - '!tests/Dockerfile'
  pull_request:
    paths:
    - 'openjdk-8-windowsservercore/**'
    - 'tests/**'
    - github-action.ps1
    - '!tests/*.bash'
    - '!tests/Dockerfile'

env:
  DOCKER_PUSH: "true"

jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Check out code
      uses: actions/checkout@v2
    - name: Build Images
      run: .\github-action.ps1 openjdk-8-windowsservercore ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }}
      shell: pwsh
